### ISSUE TITLE
Sample usage in readme throws exception

### ISSUE THREAD

**Issue by kennwilson** [Insightly/insightly-ruby#24]
I'm just getting started with the Insightly API in general and this gem in particular. I've installed the gem and loaded up a Rails console to begin experimenting. 

I started with the sample usage in the readme and immediately ran into an error:

```
$ rails console
[1] pry(main)> Insightly2.api_key = < my actual API key here >
=> "< my actual API key >"
[2] pry(main)> contacts = Insightly2.client.get_contacts
SyntaxError: /usr/local/lib/ruby/gems/2.0.0/gems/insightly2-0.1.7/lib/insightly2/dsl/comments.rb:10: syntax error, unexpected ')'
/usr/local/lib/ruby/gems/2.0.0/gems/insightly2-0.1.7/lib/insightly2/dsl/comments.rb:21: syntax error, unexpected ','
def create_comment_attachment(id:, filename:)
                                  ^
/usr/local/lib/ruby/gems/2.0.0/gems/insightly2-0.1.7/lib/insightly2/dsl/comments.rb:32: syntax error, unexpected ')'
/usr/local/lib/ruby/gems/2.0.0/gems/insightly2-0.1.7/lib/insightly2/dsl/comments.rb:35: syntax error, unexpected keyword_end, expecting end-of-input
from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
```

My versions:
- Ruby 2.0.0 (via Homebrew)
- Insightly2 0.1.7

Thanks.

**Comment by brianinsightly** [comment]
HI Ken,

The ruby library was written by one of our customers, so your best bet is
to report an issue via github so the developer can get in touch directly
(we're not a ruby shop here).

Thanks,

Brian McConnell
Insightly Engineering Team

**Comment by kennwilson** [comment]
?
This *is* Github.

Is there another copy of this repository somewhere on Github that I should be using for issues instead of this one?

**Comment by brianinsightly** [comment]
Oh,

My bad. I've been on zendesk all day and just assumed this came from
github.

Glad it's friday :)

The developer who worked on this is generally pretty responsive. I'd help
you but I've never touched Ruby (mostly work in Python and .Net here).

Thanks again for using Insightly.

Brian McConnell

**Comment by kennwilson** [comment]
We're going on 6 weeks on this. We've already committed to an annual Insightly account and I need to get working on an integration with our ecommerce site. 

Does the original developer of this gem monitor these Github issues? If not, how does one normally report issues?

**Comment by kennwilson** [comment]
@dior001 It appears you're the original author of this gem? Drop me an email at kenn at colettehq dot com if you're interested in picking up a little contract work on the integration we need. Thanks.

**Comment by dior001** [comment]
@kennwilson @brianinsightly apologies this issue slipped past my radar. Kenn I will investigate the reported issue this evening and respond to your email.

**Comment by kennwilson** [comment]
For anyone else who comes across this, the exception is due to this gem requiring Ruby 2.1, not 2.0 as stated (at the time of this writing) in the readme.
